# Generated by Django 4.1.13 on 2024-07-22 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DangKyLich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayCoHieuLuc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Kip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50)),
                ('gioVao', models.TimeField()),
                ('gioRa', models.TimeField()),
                ('moTa', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ngay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=20)),
                ('moTa', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoTen', models.CharField(max_length=255)),
                ('ngaySinh', models.DateField()),
                ('diaChi', models.CharField(max_length=255)),
                ('soDT', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LichLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('moTa', models.TextField(blank=True, null=True)),
                ('thuong', models.IntegerField()),
                ('kip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_attendance_app.kip')),
                ('ngay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_attendance_app.ngay')),
            ],
        ),
        migrations.CreateModel(
            name='DiemDanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('gioVao', models.TimeField()),
                ('gioRa', models.TimeField()),
                ('dangKyLich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_attendance_app.dangkylich')),
            ],
        ),
        migrations.AddField(
            model_name='dangkylich',
            name='lichLamViec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_attendance_app.lichlamviec'),
        ),
        migrations.AddField(
            model_name='dangkylich',
            name='nhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_attendance_app.nhanvien'),
        ),
    ]
