# Generated by Django 4.1.13 on 2024-07-30 01:57

import data_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DangKyLich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_co_hieu_luc', models.DateTimeField()),
                ('ngay_het_han', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Kip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50)),
                ('gio_vao', models.TimeField()),
                ('gio_ra', models.TimeField()),
                ('mota', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ImageField(upload_to=data_app.models.get_upload_to)),
                ('ngay_them', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ngay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=20)),
                ('mota', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=255)),
                ('ngay_sinh', models.DateField()),
                ('dia_chi', models.CharField(max_length=255)),
                ('so_dt', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MoHinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('ngay_train', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ds_mau', models.ManyToManyField(related_name='ds_mohinh', to='data_app.mau')),
            ],
        ),
        migrations.AddField(
            model_name='mau',
            name='nhanvien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.nhanvien'),
        ),
        migrations.CreateModel(
            name='LuongNhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muc_luong', models.IntegerField()),
                ('ngay_co_hieu_luc', models.DateField()),
                ('nhanvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='LichLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('mota', models.CharField(blank=True, max_length=255, null=True)),
                ('thuong', models.IntegerField(default=0)),
                ('kip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.kip')),
                ('ngay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.ngay')),
            ],
        ),
        migrations.CreateModel(
            name='DiemDanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('gio_vao', models.TimeField()),
                ('gio_ra', models.TimeField(null=True)),
                ('ca_lam_viec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.dangkylich')),
            ],
        ),
        migrations.AddField(
            model_name='dangkylich',
            name='lich_lam_viec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.lichlamviec'),
        ),
        migrations.AddField(
            model_name='dangkylich',
            name='nhanvien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.nhanvien'),
        ),
    ]
